version: '3.1'

services:
  web:
    build: .
    container_name: mybard_web
    restart: always
    ports:
      - "5000:5000"
    networks:
      - mybard_network
    depends_on:
      - db

  db:
    image: postgres
    container_name: mybard_postgres
    restart: always
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mybard_network

volumes:
  postgres_data:

networks:
  mybard_network:
